### ISSUE TITLE
Tweet Character Length Error

### ISSUE THREAD

**Issue by ghost** [magic-coding/pytweet#1]
The maximum amount of characters you can use in your tweet is 140 and not 144. Check it up!
Cheers!

**Comment by malnafei** [comment]
Good catching.
I fixed code in latest commit [8a30dd2](https://github.com/magic-coding/pytweet/commit/8a30dd2c96ea0cf2f9330be6380fdcdf9ff206f4)

Thank you.

**Comment by ghost** [comment]
Nice!
